apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: akmm74jtg-nodejs 
  janus-idp.io/tekton: akmm74jtg-nodejs
  backstage.io/kubernetes-id: akmm74jtg-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: akmm74jtg-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml