apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: akmm74jtg-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: akmm74jtg-nodejs 
  name: akmm74jtg-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: akmm74jtg-nodejs 
